### ISSUE TITLE
如果view超过一屏幕外层套个scrollview如何解决手势冲突？

### ISSUE THREAD

**Issue by MIkeeJY** [landsnail/VerticalViewPager#2]
我的item的布局超出了一屏幕了，外层套个scrollview会发生滑动不灵敏，事件被scrollview吃掉了。。

**Comment by MIkeeJY** [comment]
已经解决 我用了别家修改版的verticalviewpager

**Comment by memorise** [comment]
@MIkeeJY 用哪一家解决的？

**Comment by landsnail** [comment]
这个布局就是为了超过一层解决的。
我提供了子布局，防止ScrollView吃掉所有的时间。
要用我提供的定制子布局文件。

**Comment by MIkeeJY** [comment]
@memorise  https://github.com/CiprianU/VerticalViewPager
因为即使嵌套了landsnail  提供的scrollviewForTop 依然滑动不是很流畅 用了这个人修改过的之后
外加@ landsnail 提供子布局 就ok了
